apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upload-pipeline
  labels:
    app: my-app
spec:
  resources:
    - name: s3-bucket
      type: storage
  tasks:
    - name: test
      taskRef:
        name: upload-task
      resources:
        outputs:
          - name: reports
            resource: s3-bucket