---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-storage-bucket
type: kubernetes.io/opaque
stringData:
  boto-config: |
    [Credentials]
    aws_access_key_id = AWS_ACCESS_KEY_ID
    aws_secret_access_key = AWS_SECRET_ACCESS_KEY
    [s3]
    host = s3.us-east-1.amazonaws.com
    use-sigv4 = True
    [Boto]
    https_validate_certificates = True
    [GSUtil]
    prefer_api = xml