# This SecretDefinition is an example of how the Secret can be pulled from Hashicorp Vault, with https://github.com/tuenti/secrets-manager

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: tekton-storage-bucket
  labels:
    app: my-app
spec:
  type: Opaque
  name: tekton-storage-bucket
  keysMap:
    boto_config:
      path: secret/data/kubernetes/tekton-storage
      key: boto_config
